=== TsiupiakPavlo/TA_Lab_Java/14_XML/src/main/resources/xml/sites.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="sites">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="site" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" />
                            <xs:element name="site_type" type="xs:string" />
                            <xs:element name="chars">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="mailPresence" type="xs:boolean" />
                                        <xs:element name="newsPresence" type="xs:boolean" />
                                        <xs:element name="archivePresence" type="xs:boolean" />
                                        <xs:element name="vote" type="xs:string" />
                                        <xs:element name="payment" type="xs:boolean" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="auth_access" type="xs:boolean" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TsiupiakPavlo/TA_Lab_Java/14_XML/src/main/resources/xml/sites.xml
<?xml version="1.0" encoding="UTF-8"?>
<sites xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sites.xsd">
    <site>
        <title>MySite</title>
        <site_type>NEWS</site_type>
        <chars>
            <mailPresence>true</mailPresence>
            <newsPresence>true</newsPresence>
            <archivePresence>false</archivePresence>
            <vote>YES</vote>
            <payment>true</payment>
        </chars>
        <auth_access>true</auth_access>
    </site>
    <site>
        <title>YourSite</title>
        <site_type>ADVERTISING</site_type>
        <chars>
            <mailPresence>false</mailPresence>
            <newsPresence>false</newsPresence>
            <archivePresence>false</archivePresence>
            <vote>NO</vote>
            <payment>false</payment>
        </chars>
        <auth_access>false</auth_access>
    </site>
    <site>
        <title>SomeSite</title>
        <site_type>PORTAL</site_type>
        <chars>
            <mailPresence>true</mailPresence>
            <newsPresence>false</newsPresence>
            <archivePresence>false</archivePresence>
            <vote>YES</vote>
            <payment>true</payment>
        </chars>
        <auth_access>true</auth_access>
    </site>
</sites>
